/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "pin_manager.h"
#include "seven_seg_display.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

uint16 btnDebounce = 0, counter = 0;
boolean btnFlagPlayPause = 0, flagResetDig = 0, playPause = 0;
uint8 dig1 = 0, dig2 = 0,  dig3 = 0,  dig4 = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    PIN_MANAGER_Initialize();

    Init_Seven_Segment();

    while(1)
    {
//        IfxPort_setPinPadDriver(&MODULE_P33, 0, IfxPort_PadDriver_cmosAutomotiveSpeed1);
//
//        MODULE_P00.IOCR0.B.PC0 = 0x10;
//        MODULE_P00.LPCR0.B.PS1 = 0;
//        MODULE_P00.OMR.U = 0x10001;

        if(IfxPort_getPinState(BUTTON) == 0) //B
        {


            if(btnDebounce == 0 && flagResetDig == 0) //B --> C
            {
                if(btnFlagPlayPause == 0)
                {
                    btnDebounce = 10;
                    btnFlagPlayPause = 1;
                }
                else
                {

                    playPause  = !playPause ;
                    btnDebounce = 0;
                    btnFlagPlayPause = 0;
                    flagResetDig = 1;

                }
            }
            else if(btnDebounce == 0 && flagResetDig == 1) //B --> D
            {
                if(btnFlagPlayPause == 0)
                {
                    btnDebounce = 900;
                    btnFlagPlayPause = 1;
                }
                else
                {

                    dig1 = dig2 = dig3 = dig4 = 0;
                    btnDebounce = 0;
                    btnFlagPlayPause = 0;
                    flagResetDig = 0;
                    counter = 0;

                }

            }
            else
            {
                btnDebounce--;
            }



        }
        else //B
        {
            btnDebounce = 0;
            btnFlagPlayPause = 0;
            flagResetDig = 0;
        }


        if (playPause)
        {
            if (counter > 100)
            {
                counter = 0;

                if (dig4 >= 9)
                {
                    dig4 = 0;
                    if (dig3 >= 9)
                    {
                        dig3 = 0;
                        if (dig2 >= 9)
                        {
                            dig2 = 0;
                            if (dig1 >= 9)
                            {
                                dig4 = 0;
                                dig3 = 0;
                                dig2 = 0;
                                dig1 = 0;

                            }else{
                                dig1++;
                            }
                        }else{
                            dig2++;
                        }
                    }else{
                        dig3++;
                    }
                }else{
                    dig4++;
                }
            }
            else
            {
                counter++;
            }

        }



        Set_Seven_Segment_Value(DIGIT_1, dig1);
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 1));    /*! Wait 1000 milliseconds            */
        Set_Seven_Segment_Value(DIGIT_2, dig2);
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 1));    /*! Wait 1000 milliseconds            */
        Set_Seven_Segment_Value(DIGIT_3, dig3);
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 1));    /*! Wait 1000 milliseconds            */
        Set_Seven_Segment_Value(DIGIT_4, dig4);
        waitTime(IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 1));    /*! Wait 1000 milliseconds            */
    }
    return (1);
}
