################################################################################
# Automatically-generated file. Do not edit!
################################################################################

I_SRCS := 
S_SRCS := 
ASM_UPPER_SRCS := 
CPCP_SRCS := 
ASM_SRCS := 
C_SRCS := 
MCS_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
I_DEPS := 
PCP_S := 
EXECUTABLES := 
OBJS := 
C_DEPS := 
CPCP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/AppSw/Tricore/Demo_Illd \
src/AppSw/Tricore/Main \
src/BaseSw/Infra/Platform/Tricore/Compilers \
src/BaseSw/Service/CpuGeneric/If \
src/BaseSw/Service/CpuGeneric/StdIf \
src/BaseSw/Service/CpuGeneric/SysSe/Bsp \
src/BaseSw/Service/CpuGeneric/SysSe/Comm \
src/BaseSw/Service/CpuGeneric/SysSe/General \
src/BaseSw/Service/CpuGeneric/SysSe/Math \
src/BaseSw/Service/CpuGeneric/SysSe/Time \
src/BaseSw/iLLD/TC29B/Tricore/Asclin/Asc \
src/BaseSw/iLLD/TC29B/Tricore/Asclin/Lin \
src/BaseSw/iLLD/TC29B/Tricore/Asclin/Spi \
src/BaseSw/iLLD/TC29B/Tricore/Asclin/Std \
src/BaseSw/iLLD/TC29B/Tricore/Ccu6/Icu \
src/BaseSw/iLLD/TC29B/Tricore/Ccu6/PwmBc \
src/BaseSw/iLLD/TC29B/Tricore/Ccu6/PwmHl \
src/BaseSw/iLLD/TC29B/Tricore/Ccu6/Std \
src/BaseSw/iLLD/TC29B/Tricore/Ccu6/TPwm \
src/BaseSw/iLLD/TC29B/Tricore/Ccu6/Timer \
src/BaseSw/iLLD/TC29B/Tricore/Ccu6/TimerWithTrigger \
src/BaseSw/iLLD/TC29B/Tricore/Cif/Cam \
src/BaseSw/iLLD/TC29B/Tricore/Cif/Std \
src/BaseSw/iLLD/TC29B/Tricore/Cpu/CStart \
src/BaseSw/iLLD/TC29B/Tricore/Cpu/Irq \
src/BaseSw/iLLD/TC29B/Tricore/Cpu/Std \
src/BaseSw/iLLD/TC29B/Tricore/Cpu/Trap \
src/BaseSw/iLLD/TC29B/Tricore/Dma/Dma \
src/BaseSw/iLLD/TC29B/Tricore/Dma/Std \
src/BaseSw/iLLD/TC29B/Tricore/Dsadc/Dsadc \
src/BaseSw/iLLD/TC29B/Tricore/Dsadc/Rdc \
src/BaseSw/iLLD/TC29B/Tricore/Dsadc/Std \
src/BaseSw/iLLD/TC29B/Tricore/Dts/Dts \
src/BaseSw/iLLD/TC29B/Tricore/Dts/Std \
src/BaseSw/iLLD/TC29B/Tricore/Ebu/BFlashSpansion \
src/BaseSw/iLLD/TC29B/Tricore/Ebu/BFlashSt \
src/BaseSw/iLLD/TC29B/Tricore/Ebu/Dram \
src/BaseSw/iLLD/TC29B/Tricore/Ebu/Sram \
src/BaseSw/iLLD/TC29B/Tricore/Ebu/Std \
src/BaseSw/iLLD/TC29B/Tricore/Emem/Std \
src/BaseSw/iLLD/TC29B/Tricore/Eray/Eray \
src/BaseSw/iLLD/TC29B/Tricore/Eray/Std \
src/BaseSw/iLLD/TC29B/Tricore/Eth/Phy_Pef7071 \
src/BaseSw/iLLD/TC29B/Tricore/Eth/Std \
src/BaseSw/iLLD/TC29B/Tricore/Fce/Crc \
src/BaseSw/iLLD/TC29B/Tricore/Fce/Std \
src/BaseSw/iLLD/TC29B/Tricore/Fft/Fft \
src/BaseSw/iLLD/TC29B/Tricore/Fft/Std \
src/BaseSw/iLLD/TC29B/Tricore/Flash/Std \
src/BaseSw/iLLD/TC29B/Tricore/Gpt12/IncrEnc \
src/BaseSw/iLLD/TC29B/Tricore/Gpt12/Std \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Atom/Pwm \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Atom/PwmHl \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Atom/Timer \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Std \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Tim/In \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Tom/Pwm \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Tom/PwmHl \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Tom/Timer \
src/BaseSw/iLLD/TC29B/Tricore/Gtm/Trig \
src/BaseSw/iLLD/TC29B/Tricore/Hssl/Hssl \
src/BaseSw/iLLD/TC29B/Tricore/Hssl/Std \
src/BaseSw/iLLD/TC29B/Tricore/I2c/I2c \
src/BaseSw/iLLD/TC29B/Tricore/I2c/Std \
src/BaseSw/iLLD/TC29B/Tricore/Iom/Driver \
src/BaseSw/iLLD/TC29B/Tricore/Iom/Std \
src/BaseSw/iLLD/TC29B/Tricore/Msc/Msc \
src/BaseSw/iLLD/TC29B/Tricore/Msc/Std \
src/BaseSw/iLLD/TC29B/Tricore/Mtu/Std \
src/BaseSw/iLLD/TC29B/Tricore/Multican/Can \
src/BaseSw/iLLD/TC29B/Tricore/Multican/Std \
src/BaseSw/iLLD/TC29B/Tricore/Port/Io \
src/BaseSw/iLLD/TC29B/Tricore/Port/Std \
src/BaseSw/iLLD/TC29B/Tricore/Psi5/Psi5 \
src/BaseSw/iLLD/TC29B/Tricore/Psi5/Std \
src/BaseSw/iLLD/TC29B/Tricore/Psi5s/Psi5s \
src/BaseSw/iLLD/TC29B/Tricore/Psi5s/Std \
src/BaseSw/iLLD/TC29B/Tricore/Qspi/SpiMaster \
src/BaseSw/iLLD/TC29B/Tricore/Qspi/SpiSlave \
src/BaseSw/iLLD/TC29B/Tricore/Qspi/Std \
src/BaseSw/iLLD/TC29B/Tricore/Scu/Std \
src/BaseSw/iLLD/TC29B/Tricore/Sent/Sent \
src/BaseSw/iLLD/TC29B/Tricore/Sent/Std \
src/BaseSw/iLLD/TC29B/Tricore/Smu/Std \
src/BaseSw/iLLD/TC29B/Tricore/Src/Std \
src/BaseSw/iLLD/TC29B/Tricore/Stm/Std \
src/BaseSw/iLLD/TC29B/Tricore/Stm/Timer \
src/BaseSw/iLLD/TC29B/Tricore/Vadc/Adc \
src/BaseSw/iLLD/TC29B/Tricore/Vadc/Std \
src/BaseSw/iLLD/TC29B/Tricore/_Impl \
src/BaseSw/iLLD/TC29B/Tricore/_Lib/DataHandling \
src/BaseSw/iLLD/TC29B/Tricore/_Lib/InternalMux \
src/BaseSw/iLLD/TC29B/Tricore/_PinMap \

